Repository OpenVoiceOS/ovos-skill-homescreen, pull requests merged in 2022-10, with the labels that each got.

#42 setup.py tweaks and skill_id fix
  MANIFEST.in
  __init__.py
  setup.py
Labels: bug, packaging

#46 Add/translations
  ui/translations/AddCardOverlay_de.ts
  ui/translations/BoxesPage_de.ts
  ui/translations/GridBox_de.ts
  ui/translations/idle_de.ts
  ui/translations/skill-ovos-homescreen.openvoiceos_de.qm
  vocab/de-de/change.wallpaper.intent
  vocab/es-es/change.wallpaper.intent
  vocab/fr-fr/change.wallpaper.intent
  vocab/it-it/change.wallpaper.intent
  vocab/nl-nl/change.wallpaper.intent
  vocab/pt-pt/change.wallpaper.intent
Labels: enhancement, lang support

#47 Feat/workflows
  .github/workflows/auto_translate.yml
  .github/workflows/build_tests.yml
  .github/workflows/dev2master.yml
  .github/workflows/install_tests.yml
  .github/workflows/license_tests.yml
  .github/workflows/prepare_skillstore.yml
  .github/workflows/unit_tests.yml
  .gitignore
  scripts/prepare_skillstore.py
  scripts/translate.py
  test/license_tests.py
  test/osm_tests.py
  test/plugin_tests.py
  test/unittests/test_skill_loading.py
Labels: automations

#48 Locale
  locale/de-de/change.wallpaper.intent
  locale/en-us/change.wallpaper.intent
  locale/es-es/change.wallpaper.intent
  locale/fr-fr/change.wallpaper.intent
  locale/it-it/change.wallpaper.intent
  locale/nl-nl/change.wallpaper.intent
  locale/pt-pt/change.wallpaper.intent
  requirements.txt
  scripts/migrate_locale.py
  test/osm_tests.py
  test/plugin_tests.py
Labels: refactor
