Repository OpenVoiceOS/ovos-skill-homescreen, pull requests merged in 2024-01, with the labels that each got.

#101 working for ovos-utils 0.1.0
  __init__.py
Labels: packaging

#100 fix/log_spam
  __init__.py
  requirements.txt
Labels: bug

#97 Update link
  README.md
Labels: documentation

#102 fix markup indentation
  README.md
Labels: bug, automations

#103 add markdown content type
  setup.py
Labels: bug, automations
